version: 2

updates:
  - package-ecosystem: npm
    directories:
      - .npm
    versioning-strategy: increase
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      deps:
        applies-to: version-updates
        dependency-type: production
      deps-dev:
        dependency-type: development
      security:
        applies-to: security-updates
        dependency-type: production
    commit-message:
      prefix: npm
      prefix-development: npm
      include: scope
